def on_forever():
    pins.digital_write_pin(DigitalPin.P0, 1)
    basic.show_string("G")
    basic.pause(5000)
    pins.digital_write_pin(DigitalPin.P0, 0)
    basic.clear_screen()
    pins.digital_write_pin(DigitalPin.P1, 1)
    basic.show_string("Y")
    basic.pause(2000)
    pins.digital_write_pin(DigitalPin.P1, 0)
    basic.clear_screen()
    pins.digital_write_pin(DigitalPin.P2, 1)
    basic.show_string("R")
    basic.pause(7000)
    pins.digital_write_pin(DigitalPin.P2, 0)
    basic.clear_screen()
basic.forever(on_forever)
