basic.forever(function () {
    pins.digitalWritePin(DigitalPin.P0, 1)
    basic.showString("G")
    basic.pause(5000)
    pins.digitalWritePin(DigitalPin.P0, 0)
    basic.clearScreen()
    pins.digitalWritePin(DigitalPin.P1, 1)
    basic.showString("Y")
    basic.pause(2000)
    pins.digitalWritePin(DigitalPin.P1, 0)
    basic.clearScreen()
    pins.digitalWritePin(DigitalPin.P2, 1)
    basic.showString("R")
    basic.pause(7000)
    pins.digitalWritePin(DigitalPin.P2, 0)
    basic.clearScreen()
})
